english = {
    "menu": {
        "o0": "Home",
        "o1": "Squad",
        "o2": "Tactic",
        "o3": "Development",
        "o4": "Hide menu",
        "o5": "Statistics",
        "o6": "Metrics",
        "o7": "Compare",
        "o8": "Scouting",
        "o9": "Employees",
        "o10": "Settings",
        "o11": "Language",
        "o12": "Help",
        "oaux1": "Statistics and Metrics",
        "t0": "Home Page",
        "t1": "Show your squad",
        "t2": "Show your tactic",
        "t3": "Show flaws of your players",
        "t4": "Show menu",
        "t5": "Show statistics",
        "t6": "Show metrics",
        "t7": "Comparation between players",
        "t8": "Show scouted players",
        "t9": "Show your employees",
        "t10": "Open Settings",
        "t11": "Open Languages",
        "t12": "Open Help",
        "taux1": "Show Statistics and Metrics",
        "g0": "Actual Squad",
        "g1": "Scouting",
        "g2": "Old Squad",
    },
    "pages": {
        "p1": {},
        "p2": {},
        "p3": {},
        "p4": {},
        "p5": {},
        "p6": {},
        "p7": {
            "btn_compare_s": "Select Statistics",
            "btn_compare_a": "Select Attributes",
            "btn_compare_d": "Send Data",
        },
        "p8": {},
        "p9": {},
        "p10": {
            "process_btn": "Process Data"
        },
        "p11": {},
        "p12": {},
        "p13": {},
    },
    "left_content": {
        "b1": "Load squad file",
        "b2": "Load scouting file"
    },
    "right_content": {
        "b1": "Slide to stats filters",
        "b2": "Slide to attrs filters",
        "b3": "Filter Data",
    },
    "title_buttons_tooltips": {
        "b1": "Refresh",
        "b2": "Scouting filters",
        "b3": "Minimize app",
        "b4": "Maximize app",
        "b5": "Close app",
    },
}

column_headers = {
    "h": {
        "h1": "Name",
        "h2": "Age",
        "h3": "Personality",
        "h4": "Position",
        "h5": "Height",
        "h6": "Preferred Foot",
        "h7": "NoB",
        "h8": "Birth City",
        "h9": "Expires",
        "h10": "Transfer Value",
        "h11": "Salary",
        "h12": "Mins",
        "s1": "Svt",
        "s2": "Svp",
        "s3": "Svh",
        "s4": "Conc",
        "s5": "Pas %",
        "s6": "Ps C/90",
        "s7": "K Tck",
        "s8": "Tck R",
        "s9": "Int/90",
        "s10": "Hdr %",
        "s11": "Hdrs W/90",
        "s12": "Fls",
        "s13": "K Ps/90",
        "s14": "Ch C/90",
        "s15": "Gls/90",
        "s16": "Asts/90",
        "s17": "Shot %",
        "s18": "Drb/90",
        "s19": "Shot/90",
        "s20": "Cr C/A",
        "s21": "Cr C",
        "s22": "ShT/90",
        "s23": "Dist/90",
        "s24": "Gls",
        "s25": "Ast",
        "s26": "Tall",
        "s27": "Tcon/90",
        "s28": "Ps A/90",
        "s29": "Pens S",
        "s30": "Av Rat",
        "s31": "Tck",
        "s32": "Gl Mst",
        "a1": "Acc",
        "a2": "Wor",
        "a3": "Vis",
        "a4": "Thr",
        "a5": "Tec",
        "a6": "Tea",
        "a7": "Tck",
        "a8": "Str",
        "a9": "Sta",
        "a10": "TRO",
        "a11": "Ref",
        "a12": "Pun",
        "a13": "Pos",
        "a14": "Pen",
        "a15": "Pas",
        "a16": "Pac",
        "a17": "1v1",
        "a18": "OtB",
        "a19": "Nat",
        "a20": "Mar",
        "a21": "L Th",
        "a22": "Lon",
        "a23": "Ldr",
        "a24": "Kic",
        "a25": "Jum",
        "a26": "Hea",
        "a27": "Han",
        "a28": "Fre",
        "a29": "Fla",
        "a30": "Fir",
        "a31": "Fin",
        "a32": "Ecc",
        "a33": "Dri",
        "a34": "Det",
        "a35": "Dec",
        "a36": "Cro",
        "a37": "Cor",
        "a38": "Cnt",
        "a39": "Cmp",
        "a40": "Com",
        "a41": "Cmd",
        "a42": "Bra",
        "a43": "Bal",
        "a44": "Ant",
        "a45": "Agi",
        "a46": "Agg",
        "a47": "Aer",
    },
    "a": {
        "au0": "<- EDIT",
        "au1": "Role Ideal",
        "au2": "Role Score",
        "au3": "Frol",
        "au4": "Role 1S",
        "au5": "Srol",
        "au6": "Role 2S",
        "au7": "Trol",
        "au8": "Role 3S",
        "au9": "Preferred training",
    },
}

positions = {
    "p1": "GK-De",
    "p2": "SW-De",
    "p3": "SW-Su",
    "p4": "SW-At",
    "p5": "BPD-De",
    "p6": "BPD-Co",
    "p7": "BPD-St",
    "p8": "CD-De",
    "p9": "CD-Co",
    "p10": "CD-St",
    "p11": "L-Su",
    "p12": "WCB-De",
    "p13": "WCB-Su",
    "p14": "WCB-At",
    "p15": "NCB-De",
    "p16": "NCB-Co",
    "p17": "NCB-St",
    "p18": "CWB-Su",
    "p19": "CWB-At",
    "p20": "WB-De",
    "p21": "WB-Su",
    "p22": "WB-At",
    "p23": "IWB-De",
    "p24": "IWB-Su",
    "p25": "IWB-At",
    "p26": "NFB-De",
    "p27": "FB-De",
    "p28": "FB-Su",
    "p29": "FB-At",
    "p30": "A-De",
    "p31": "HB-De",
    "p32": "DM-De",
    "p33": "DM-Su",
    "p34": "REG-Su",
    "p35": "VOL-Su",
    "p36": "VOL-At",
    "p37": "DLP-De",
    "p38": "DLP-Su",
    "p39": "BWM-De",
    "p40": "BWM-Su",
    "p41": "CM-De",
    "p42": "CM-Su",
    "p43": "CM-At",
    "p44": "CAR-Su",
    "p45": "BBM-Su",
    "p46": "RPM-Su",
    "p47": "MEZ-Su",
    "p48": "MEZ-At",
    "p49": "AT-Su",
    "p50": "AT-At",
    "p51": "WM-De",
    "p52": "WM-Su",
    "p53": "WM-At",
    "p54": "DW-De",
    "p55": "DW-Su",
    "p56": "WP-Su",
    "p57": "WP-At",
    "p58": "EG-Su",
    "p59": "AM-Su",
    "p60": "AM-At",
    "p61": "T-At",
    "p62": "SS-At",
    "p63": "W-Su",
    "p64": "W-At",
    "p65": "IF-Su",
    "p66": "IF-At",
    "p67": "IW-Su",
    "p68": "IW-At",
    "p69": "RMD-At",
    "p70": "WT-Su",
    "p71": "WT-At",
    "p72": "TF-Su",
    "p73": "TF-At",
    "p74": "DLF-Su",
    "p75": "DLF-At",
    "p76": "PF-De",
    "p77": "PF-Su",
    "p78": "PF-At",
    "p79": "CF-Su",
    "p80": "CF-At",
    "p81": "P-At",
    "p82": "AF-At",
    "p83": "F9-Su",
}
