stats_list_en = {
    "Mins": "Minutes",
    "Svt": "Saves Tipped",
    "Svp": "Saves Parried",
    "Svh": "Saves Held",
    "Conc": "Conceded",
    "Pas %": "% Passes",
    "Ps C/90": "Completed Passes / 90'",
    "K Tck": "Key Tackles",
    "Tck R": "Tackles Ratio",
    "Int/90": "Interceptions / 90",
    "Hdr %": "% Headers",
    "Hdrs W/90": "Headers Won / 90",
    "Fls": "Fouls",
    "K Ps/90": "Key Passes / 90",
    "Ch C/90": "Chances Created / 90",
    "Gls/90": "Goals / 90",
    "Asts/90": "Assists / 90",
    "Shot %": "% Shots",
    "Drb/90": "Dribbles / 90",
    "Shot/90": "Shots / 90",
    "Cr C": "Crosses Completed",
    "Cr C/A": "Crosses Completed vs Attempts",
    "ShT/90": "Shots on Target / 90",
    "Dist/90": "Distance Covered / 90",
    "Gls": "Goals",
    "Ast": "Assits",
    "Tall": "Team allowed",
    "Tcon/90": "Team conceded / 90",
    "Ps A/90": "Passes Attempted / 90",
    "Pens S": "Penalties Scored",
    "Av Rat": "Average Rating",
    "Tck": "Tackles / 90",
    "Gl Mst": "Mistakes costing goals",
    "Salary": "Salary",
    "Age": "Age",
}

stats_list_es = {
    "Min": "Minutos",
    "BDs": "Balones Despejados",
    "BRe": "Balones Rechazados",
    "BAt": "Balones Atajados",
    "Enc": "Encajados",
    "% Pase": "% Pases",
    "Ps C/90": "Pases Completados / 90",
    "Ent Cl": "Entradas Clave",
    "Ent P": "Promedio Entradas",
    "Rob/90": "Robos / 90",
    "Rcg %": "% Cabezazos",
    "Cab G/90": "Cabezazos Ganados / 90",
    "FC": "Faltas Cometidas",
    "Pas Clv/90": "Pases Clave / 90",
    "Oc C/90": "Ocasiones Creadas / 90",
    "Gol/90": "Goles / 90",
    "Asis/90": "Asistencias / 90",
    "% disparos": "% Disparos",
    "Reg/90": "Regates / 90",
    "Tir/90": "Tiros / 90",
    "Cen.C/I": "Centros Completados vs Intentados",
    "Cen.Com": "Centros Completados",
    "TirP/90": "Tiros a puerta / 90",
    "Dist/90": "Distancia Recorrida / 90",
    "Gol": "Goles",
    "Asis": "Asistencias",
    "EnEq": "Encajados Equipo",
    "EnEq/90": "Encajados Equipo / 90",
    "Ps I/90": "Pases Intentados / 90",
    "Pen M": "Penalties Marcados",
    "Media": "Media",
    "Gl Err": "Errores que costaron goles",
    "Ent": "Entradas / 90",
    "Sueldo": "Sueldo",
    "Edad": "Edad",
}
